# Generated by Django 5.1.3 on 2024-12-07 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_alter_utilisateurbibliotheque_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.livre'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateurbibliotheque',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
