# Generated by Django 5.1.3 on 2024-12-07 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_alter_emprunt_date_emprunt_alter_emprunt_date_retour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurbibliotheque',
            name='utilisateur',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_bibliotheque', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts_utilisateur', to='bibliotheque.livre'),
        ),
    ]
