# Generated by Django 5.1.3 on 2024-12-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_alter_utilisateurbibliotheque_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres/'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='livre',
            name='exemplaires_disponibles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
