# Generated by Django 5.1.3 on 2024-12-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_livre_image_alter_livre_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
